### ISSUE TITLE
Testing: Output Formats module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/OutputFormats#3]
This simple module adds a select menu to resource pages (item, item set, media) that allows users to view the resources in a different format. The available formats are:

- JSON-LD (application/ld+json)
- Notation3 (text/n3)
- N-Triples (application/n-triples)
- RDF/XML (application/rdf+xml)
- Turtle (text/turtle)

After installing this module, you should see the format selector and a "View in the selected format" button at the bottom of the following pages:

- Items browse (admin and public site)
- Item show (admin and public site)
- Item sets browse (admin and public site)
- Item set show (admin and public site)
- Media browse (admin)
- Media show (admin)

Clicking on the button should open a new tab that contains the selected format. To enable the format selector on public sites, go to site "Settings" > "Output formats" and check "Add output format selector to resource pages".

**Comment by allanaaa** [comment]
Two of the output formats gave me an error from this page:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item

N-triples:

> Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/html/amayer/amayer-s/omeka-s/vendor/easyrdf/easyrdf/lib/Serialiser/Ntriples.php on line 63

And RDF/XML:

> XML Parsing Error: not well-formed
Location: http://dev.omeka.org/amayer/amayer-s/omeka-s/api-local/items?sort_by_default=&sort_order_default=&sort_by=created&sort_order=desc&page=1&site_id=1&format=rdfxml&pretty_print=1
Line Number 421, Column 1:
Unfortunately, I have not Ld. Dufferin by me for reference now, because I threw both him &amp; the
^

**Comment by allanaaa** [comment]
Same from here:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item-set/4255

and here:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item/7098#lg=1&slide=0 
(N-triples offered me a file to download; the XML error was the same.)

I'm not validating the outputs of the other options, just checking to make sure *something* is generated.

**Comment by allanaaa** [comment]
On the admin side, I get an error on the RDF/XML output for almost everything; the N-triples worked fine in all cases.

The exception was outputting from the item-sets-browse page, where the RDF/XML worked fine; and outputting RDF from a single item worked fine. So I know it's now technically possible for it to work! You may just need to account for messier data or something.

**Comment by allanaaa** [comment]
There's no indication in the design that this will be the output of the entire browse/search-results subset, or just the resources displayed with the current pagination. 

I would argue people probably want the whole results set if they want to download a dataset at all, rather than a paginated subset. Is that possible to do instead?

If not, we'll need to fix the public-side number. It appears from the outputs that you're giving me my installation-wide pagination number (in this case, 60) in the admin, as well as the installation-wide pagination number on each site, rather than the site-specific pagination setting (on this site, 18).

**Comment by jimsafley** [comment]
Unfortunately, the occasional "Maximum execution time exceeded" and "XML Parsing" errors are unavoidable. We're at the mercy of our RDF library, [EasyRDF](https://github.com/sweetrdf/easyrdf), and cleaning up the data prior to sending it to the library is unfeasible. In this case [one of the items](https://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item/16037) contains a long string that the library cannot parse correctly for whatever reason.

I made some changes that should fix the per page issue, and may fix some of the other oddities you've seen.

**Comment by allanaaa** [comment]
Sure thing. Could you write up a few other potential error cases (too-long strings, weird characters?, emojis?, ???, ...) so we can put it in the docs? If site owners can only turn it on and off, they will want guidance on how to fix any data issues their sites are generating. We'll let them know about the execution-time situation, etc., as well. 

Pagination issue is fixed, thanks!

**Comment by allanaaa** [comment]
On the design front - I would put it in the sidebar on admin view pages, rather than at the bottom of the main tab of item/set/media view:

<img width="1123" alt="Screenshot 2024-10-16 at 13 33 15" src="https://github.com/user-attachments/assets/468af94c-58ec-4b26-b41b-ca5e84544d62">

On browse pages, can you set it after the pagination - on both admin and public?:

<img width="1120" alt="Screenshot 2024-10-16 at 13 34 16" src="https://github.com/user-attachments/assets/ad066be2-4ae5-4826-8574-504b0735735f">

Then we'll see what the themes are doing to it.

**Comment by jimsafley** [comment]
It's typically invisible [control characters](https://en.wikipedia.org/wiki/Control_character) or odd [escape sequences](https://en.wikipedia.org/wiki/Escape_sequence). We don't control how the RDF library parses and composes the formats, so it's difficult to know exactly what's going on.

**Comment by jimsafley** [comment]
I've moved the admin selectors to the sidebars. I cannot move the selectors below the pagination because the `view.browse.after` event triggers before the pagination renders.

**Comment by allanaaa** [comment]
Okay, design-wise, I think if we just stick a margin-bottom:XX on the select and the button each, that should solve most design problems, whether they are side-by-side or wrapping:

<img width="406" alt="Screenshot 2024-10-17 at 10 13 22" src="https://github.com/user-attachments/assets/4f450aa5-5dac-4b2f-ba20-12c0e30b873f">
<img width="399" alt="Screenshot 2024-10-17 at 10 13 34" src="https://github.com/user-attachments/assets/2573e56e-4b21-4a5f-9c3c-10e2818560ab">

<img width="557" alt="Screenshot 2024-10-17 at 10 19 29" src="https://github.com/user-attachments/assets/b632c271-ccb3-4ae0-b904-1c45e2cf1639">
<img width="675" alt="Screenshot 2024-10-17 at 10 19 43" src="https://github.com/user-attachments/assets/070535c5-12f3-43db-a7b9-d75964b79af5">

We *could* try to show the pagination buttons and the output buttons in one big inline row in all themes, the way it's working in The Daily, but I bet nobody wants to bother. 

Special issues: 

The Daily seems to be off by about a pixel, @kimisgold, which I presume is from the border on the button - I hope we can just send a class along to fix this?
<img width="1348" alt="Screenshot 2024-10-17 at 10 17 24" src="https://github.com/user-attachments/assets/43206295-7738-4aa2-be90-ce0725172812">

Center Row is showing the output bar after the pagination, so there's probably some weird interaction there to worry about:
<img width="674" alt="Screenshot 2024-10-17 at 10 24 27" src="https://github.com/user-attachments/assets/f51af0be-d6a8-4a56-9e40-ddc3f8599c6a">

Lively and Freedom are the worst off because the select is running to the full width of the div, @nelsonamaya82 - again, is there something we can send with the module to fix this rather than modifying the themes?: 
<img width="1101" alt="Screenshot 2024-10-17 at 10 14 39" src="https://github.com/user-attachments/assets/445c5ffd-b399-4f78-939a-bd1e0d9a1339">
<img width="1272" alt="Screenshot 2024-10-17 at 10 25 56" src="https://github.com/user-attachments/assets/32952f82-a5bc-4284-a32f-b86e2381760e">

**Comment by kimisgold** [comment]
I've done some adjustments to standardize the margins around the form elements. I think they should generally look good across the themes, with a little polishing required for pixel perfect heights. Those should be done in the themes though.

**Comment by allanaaa** [comment]
The title you added on the admin side browse pages doesn't look quite right: 
<img width="1167" alt="Screenshot 2024-10-18 at 12 18 52" src="https://github.com/user-attachments/assets/02548080-8cf8-4b65-bcbc-a7b2550c6d67">

**Comment by allanaaa** [comment]
Most of the front-end stuff looks good. 

In The Daily, it sometimes appears on the same line as the pagination bits and sometimes does not:
<img width="1408" alt="Screenshot 2024-10-18 at 12 27 26" src="https://github.com/user-attachments/assets/9728526b-ee6b-47c5-895b-87e388d77439">
<img width="1402" alt="Screenshot 2024-10-18 at 12 27 54" src="https://github.com/user-attachments/assets/fefad0da-3ca3-475a-8957-01b650da0ecd">

Which I'll leave up to you whether that's a concern.

Same with the Center Row issue - it's still showing after the pagination unlike the other themes, but it's up to you to leave or not:
<img width="1235" alt="Screenshot 2024-10-18 at 12 29 46" src="https://github.com/user-attachments/assets/0f1ecb06-68a4-4529-969a-96d040861901">

And there will be an interaction with the Sharing module button if it's set to appear at the bottom of the page:
<img width="839" alt="Screenshot 2024-10-18 at 12 26 38" src="https://github.com/user-attachments/assets/247fd831-c094-47c6-9cf7-17f26427a946">

<img width="707" alt="Screenshot 2024-10-18 at 12 32 16" src="https://github.com/user-attachments/assets/62203874-605f-4b91-9359-5e6bcc3be25d">

It looks okay in some themes until you hover over it and realize there's no margin. Maybe we can put them inline? Not sure what can be done without modifying core or the Sharing module.

**Comment by kimisgold** [comment]
I've hidden the heading outside of sidebar contexts in the admin, and the input group should now float right by default, often inline with pagination. I've noticed this is not the case in a few themes, like The Daily, Papers, and Freedom. I think those themes will require their own edits to look consistent, but the default styles seem pretty reasonable to me. 

Sharing also has some issues, like the forced 45px height that doesn't seem to serve a purpose. I'll look at that separately.

**Comment by allanaaa** [comment]
That's a big improvement in most places, except Center Row, where the pagination is already right-aligned:

<img width="1162" alt="Screenshot 2024-10-18 at 15 28 37" src="https://github.com/user-attachments/assets/396bc842-e649-46a1-b6b1-36c6ed0f3cf3">

<img width="1168" alt="Screenshot 2024-10-18 at 15 31 18" src="https://github.com/user-attachments/assets/dc2778b6-9cbf-49a0-bc3f-aca354ad6180">

**Comment by nelsonamaya82** [comment]
@allanaaa this is how it looks like now on Lively with the module's default styling. Maybe for Lively and Freedom I can center it with a custom style just for these themes.
![image](https://github.com/user-attachments/assets/35d26ef0-732d-4de2-bad2-de696d04d4ba)
